library(NLP)
library(tm)
library(wordcloud2)
setwd("D:\\junior_n\\NLP\\term\\data")
cname <- file.path("D:","junior_n","NLP","term","data","co_wordcloud")
docs <- Corpus(DirSource(cname))
tospace <- content_transformer(function(x,parttern)gsub(parttern," ",x))
docs <- tm_map(docs,removePunctuation)
docs <- tm_map(docs,tospace,'/')
docs <- tm_map(docs,tospace,'@')
docs <- tm_map(docs,tospace,'\\|')
docs <- tm_map(docs,tolower)
docs <- tm_map(docs,removeNumbers)
docs <- tm_map(docs,removeWords,stopwords("english"))
docs <- tm_map(docs, stemDocument)
docs <- tm_map(docs,PlainTextDocument)
dtm <- DocumentTermMatrix(docs)
freq <- colSums(as.matrix(dtm))
ord <- order(freq,decreasing = T)
test = freq[head(ord,500)]
d <- data.frame(word = names(test),freq = test)
write.table(d,"genia_freq.csv",row.names=FALSE,col.names=FALSE,sep=",")